# Generated by Django 4.2.7 on 2023-11-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('canceled', 'Canceled'), ('featured', 'featured')], default='draft', max_length=10),
        ),
    ]
