# Generated by Django 4.2.7 on 2023-11-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
