# Generated by Django 4.2.7 on 2023-11-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_alter_eventcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='slug',
        ),
    ]
